### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by a-kaga44** [a-kaga44/runteq_portfolio#38]
## 概要
Issueベース開発のレビュー依頼用のIssue

## 実装予定の機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] パスワード変更機能
- [x] メールアドレス変更機能
- [x] 記事投稿機能
- [x] 記事共有機能
- [x] 記事閲覧機能
- [x] 記事検索・並び替え機能
- [x] 記事絞り込み・除外機能
- [x] 記事編集機能
- [x] 記事削除機能
- [x] いいね機能・いいね解除機能
- [x] プロフィール設定・編集機能
- [x] おすすめ表示（レコメンド）機能

## 必要なページ

- [x] トップページ
- [x] ユーザー登録ページ
- [x] ユーザーログインページ
- [x] パスワードリセットページ
- [x] メールアドレス変更ページ
- [x] 投稿作成ページ
- [x] 投稿作成完了ページ
- [x] 投稿詳細ページ
- [x] 投稿一覧ページ
- [x] 投稿検索ページ
- [x] マイページ
- [x] プロフィール設定ページ
- [x] 問い合わせページ
- [x] 利用規約・プライバシーポリシーページ

**Comment by Tsuchiya2** [comment]
<img width="558" alt="image" src="https://github.com/a-kaga44/runteq_portfolio/assets/61481161/9271f265-4ff5-4081-aaef-48ebeade2103">

projectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただき、上記が確認できる状態でご提出をお願いいたします。

**Comment by a-kaga44** [comment]
runteq_portfolioリポジトリとプロジェクトの紐付けを失念しておりました🙇
おそらく設定できたと思いますので、お手数をおかけしますが再度確認をお願いします。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
以下、コメントになります。

---

デプロイ、rails newなどのカードも作成しましょう。

・外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。

また、ストーリーポイント5を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5を付けているように見受けられました。ストーリーポイント1,2になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。


上記の観点も踏まえて再度、ご確認をお願いします。

**Comment by kenchasonakai** [comment]
LGTMです！
